version: "3"
services:

  svelte:
    container_name: svelte
    depends_on:
    - postgres
    - backend
    ports:
    - "8080:8080"
    build: ./svelte
    networks:
    - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
  
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "5050:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
  
  backend:
    container_name: backend
    depends_on: 
      - postgres
    ports:
    - "3000:3000"
    build: ./backend
    networks:
    - postgres

networks:
  postgres:
    driver: bridge